/** Common pay-per-call and pay-per-lead verticals. Tenants can add custom names too. */
export const PPC_VERTICALS = [
  "ACA",
  "Annuity",
  "Auto Glass",
  "Auto Insurance",
  "Auto Loan",
  "Auto Refinance",
  "Auto Repair",
  "Auto Warranty",
  "Bathroom Remodel",
  "Boat Insurance",
  "Business Insurance",
  "Business Loan",
  "Camp Lejeune",
  "Cannabis",
  "CDL Training",
  "Cleaning",
  "Commercial Insurance",
  "Credit Repair",
  "Criminal Defense",
  "Cyber Insurance",
  "Debt Consolidation",
  "Debt Settlement",
  "Dental",
  "Disability Insurance",
  "Education",
  "Electrical",
  "Family Law",
  "Final Expense",
  "Flood Insurance",
  "Flooring",
  "Garage Doors",
  "Gold IRA",
  "Gutters",
  "Hard Money",
  "Health Insurance",
  "Hearing Aids",
  "Hernia Mesh",
  "Home Insurance",
  "Home Security",
  "Home Warranty",
  "HVAC",
  "Immigration",
  "Insulation",
  "Internet",
  "IRS Tax Debt",
  "IUL",
  "Kitchen Remodel",
  "Landscaping",
  "Life Insurance",
  "Mass Tort",
  "Medicaid",
  "Medicare",
  "Medicare Advantage",
  "Medicare Supplement",
  "Mesothelioma",
  "Mold Remediation",
  "Mortgage",
  "Motorcycle Insurance",
  "Moving",
  "Painting",
  "Payday Alternative",
  "Personal Injury",
  "Personal Loan",
  "Pest Control",
  "Pet Insurance",
  "Plumbing",
  "Refinance",
  "Renters Insurance",
  "Reverse Mortgage",
  "Roofing",
  "Roundup",
  "Senior Living",
  "Siding",
  "Solar",
  "SSDI",
  "Structured Settlement",
  "Tax Relief",
  "Term Life",
  "Timeshare Exit",
  "Travel Insurance",
  "Tree Service",
  "Truck Dispatch",
  "Trucking Insurance",
  "TV / Cable",
  "Used Cars",
  "VA Disability",
  "Vision",
  "Walk-in Tubs",
  "Water Damage",
  "Water Treatment",
  "Weight Loss",
  "Windows",
  "Workers Compensation",
] as const;
